apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: sermant-injector
  namespace: {{ .Values.namespace.name }}
  labels:
    app: sermant-injector
webhooks:
  - name: sermant-injector.{{ .Values.namespace.name }}.svc.cluster.local
    clientConfig:
      caBundle: {{ .Values.injector.webhooks.caBundle }}
      service:
        name: sermant-injector
        namespace: {{ .Values.namespace.name }}
        path: "/admission"
        port: 443
    rules:
      - operations: ["CREATE"]
        resources: ["pods"]
        apiGroups: [""]
        apiVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 10
    reinvocationPolicy: Never
    failurePolicy: Fail
    objectSelector:
      matchLabels:
        sermant-injection: enabled