spring:
  application:
    name: zuul-demo

server:
  port: 8170

feign:
  hystrix:
    enabled: true

zuul:
  routes:
    consumer-demo: /consumer/**
    provider-demo: /provider/**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000