apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-demo
  labels:
    app: consumer-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-demo
  template:
    metadata:
      labels:
        app: consumer-demo
        sermant-injection: enabled
    spec:
      containers:
        - name: consumer-demo
          image: consumer-demo:1.0.0
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: default-secret