apiVersion: v1
kind: Service
metadata:
  name: zuul-demo
  labels:
    app: zuul-demo
spec:
  type: NodePort
  ports:
    - port: 8170
      nodePort: 30000
      name: zuul-test
  selector:
    app: zuul-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-demo
  labels:
    app: zuul-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zuul-demo
  template:
    metadata:
      labels:
        app: zuul-demo
        sermant-injection: enabled
    spec:
      containers:
        - name: zuul-demo
          image: zuul-demo:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8170
      imagePullSecrets:
        - name: default-secret