server:
  port: 28020
dubbo:
  application:
    name: dubbo-consumer
  protocol:
    port: 28820
  registry:
    # 模拟存量dubbo应用注册到nacos的情况，新开发的应用建议配置为 sc://127.0.0.1:30100
    address: nacos://127.0.0.1:8848